module Foggy
  autoload :Alarming, "foggy/service/alarming"
  autoload :ApplicationCatalog, "foggy/service/application_catalog"
  autoload :Backup, "foggy/service/backup"
  autoload :Baremetal, "foggy/service/baremetal"
  autoload :BlockStorage, "foggy/service/block_storage"
  autoload :Clustering, "foggy/service/clustering"
  autoload :Compute, "foggy/service/compute"
  autoload :Container, "foggy/service/container"
  autoload :DataProcessing, "foggy/service/data_processing"
  autoload :DataProtection, "foggy/service/data_protection"
  autoload :Database, "foggy/service/database"
  autoload :Dns, "foggy/service/dns"
  autoload :Identity, "foggy/service/identity"
  autoload :Image, "foggy/service/image"
  autoload :LoadBalancer, "foggy/service/load_balancer"
  autoload :Messaging, "foggy/service/messaging"
  autoload :Metering, "foggy/service/metering"
  autoload :Networking, "foggy/service/networking"
  autoload :NFVOrchestration, "foggy/service/nfv_orchestration"
  autoload :ObjectStorage, "foggy/service/object_storage"
  autoload :Orchestration, "foggy/service/orchestration"
  autoload :Search, "foggy/service/search"
  autoload :SharedFileSystems, "foggy/service/shared_file_systems"
end
